# Set true color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Don't start a login shell
set -g default-command "${SHELL}"

# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Force zsh
set-option -g default-shell /bin/zsh

# Set vi-mode
set-window-option -g mode-keys vi

# Enable mouse
set -g mouse on

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Ctrl Shift Alt vim keys to move windows
bind -n C-M-h swap-window -t -1 \; select-window -t -1
bind -n C-M-l swap-window -t +1 \; select-window -t +1

# Better key bindings for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy" \; send-keys -X clear-selection
bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "tmux paste-buffer"

# Open panes in current directory
unbind c
bind c new-window -c "#{pane_current_path}"

# Window splits keybindings and open splits in current working directory
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# tmux-sessionizer
bind-key -r f run-shell "tmux new-window tmux-sessionizer"

# tmux-windowizer
bind-key -r g run-shell "tmux new-window tmux-windowizer"

# C-w mappings for navigating between nvim and tmux
is_nvim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?nvim?x?)(diff)?$'"
bind-key -n C-w if-shell "$is_nvim" "send-keys C-w" "switch-client -T nvimtable"
bind-key -T nvimtable C-h select-pane -L \; switch-client -T root
bind-key -T nvimtable C-j select-pane -D \; switch-client -T root
bind-key -T nvimtable C-k select-pane -U \; switch-client -T root
bind-key -T nvimtable C-l select-pane -R \; switch-client -T root
bind-key -T nvimtable h select-pane -L \; switch-client -T root
bind-key -T nvimtable j select-pane -D \; switch-client -T root
bind-key -T nvimtable k select-pane -U \; switch-client -T root
bind-key -T nvimtable l select-pane -R \; switch-client -T root

# color scheme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_current_text " #{b:pane_current_command}"
set -g @catppuccin_window_text " #{b:pane_current_command}"
set -g @catppuccin_status_background none
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Load plugins
run '~/.local/share/catppuccin-tmux/catppuccin.tmux'
run '~/.local/share/tmux-sensible/sensible.tmux'
