promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
customCommands:
  - key: 'r'
    command: 'git stash show -p refs/stash@{{"{"}}{{.SelectedStashEntry.Index}}{{"}"}} | git apply -R'
    context: 'stash'
    description: 'Apply this stash in reverse'
    prompts:
    - type: 'confirm'
      title: 'Apply stash in reverse'
      body: 'Are you sure you want to apply this stash in reverse?'
